/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;

/**
 *
 * @author m.arakelian
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        JPanelCommune = new javax.swing.JPanel();
        JPanelUtilisateur = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        CheckBoxUtilisateur = new javax.swing.JCheckBoxMenuItem();
        CheckBoxCommune = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setLayout(new java.awt.CardLayout());

        JPanelCommune.setBackground(new java.awt.Color(242, 242, 42));

        javax.swing.GroupLayout JPanelCommuneLayout = new javax.swing.GroupLayout(JPanelCommune);
        JPanelCommune.setLayout(JPanelCommuneLayout);
        JPanelCommuneLayout.setHorizontalGroup(
            JPanelCommuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        JPanelCommuneLayout.setVerticalGroup(
            JPanelCommuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        MainPanel.add(JPanelCommune, "CardNameCommune");

        JPanelUtilisateur.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout JPanelUtilisateurLayout = new javax.swing.GroupLayout(JPanelUtilisateur);
        JPanelUtilisateur.setLayout(JPanelUtilisateurLayout);
        JPanelUtilisateurLayout.setHorizontalGroup(
            JPanelUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        JPanelUtilisateurLayout.setVerticalGroup(
            JPanelUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        MainPanel.add(JPanelUtilisateur, "CardNameUtilisateur");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        CheckBoxUtilisateur.setSelected(true);
        CheckBoxUtilisateur.setText("CheckBoxUtilisateur");
        CheckBoxUtilisateur.setActionCommand("");
        CheckBoxUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxUtilisateurActionPerformed(evt);
            }
        });
        jMenu2.add(CheckBoxUtilisateur);

        CheckBoxCommune.setSelected(true);
        CheckBoxCommune.setText("jCheckBoxMenuItem2");
        CheckBoxCommune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxCommuneActionPerformed(evt);
            }
        });
        jMenu2.add(CheckBoxCommune);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBoxCommuneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxCommuneActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "CardNameUtilisateur");
        
    }//GEN-LAST:event_CheckBoxCommuneActionPerformed

    private void CheckBoxUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxUtilisateurActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "CardNameCommune");
        
    }//GEN-LAST:event_CheckBoxUtilisateurActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem CheckBoxCommune;
    private javax.swing.JCheckBoxMenuItem CheckBoxUtilisateur;
    private javax.swing.JPanel JPanelCommune;
    private javax.swing.JPanel JPanelUtilisateur;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
